### ISSUE TITLE
Clean up publisher codebase

### ISSUE THREAD

**Issue by varas** [newrelic/infrastructure-publish-action#26]
## Summary

Publisher codebase is mixing up different behaviours (integrations, agent, nrjmx) sharing:
- same parsing structs
- same procedural code
- same global functions

This is:
- hard to maintain and test
- confusing, as structs are shared, you need to know which one you should be using, ie: `os` or `os_version` (depending on whether they are addressing agent/integration publish pipelines)

## Desired Behavior

Maintainable code

## Possible Solution

Split parsing structs/functions per behaviour, so there's a single structure and entry function to use for each beahaviour: agent, integration, nrjmx.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
